// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUQBsJYRohAhtbFEw7JmQix86cSya7U1c',
    appId: '1:509492408638:web:99d601c3999855c11efc6f',
    messagingSenderId: '509492408638',
    projectId: 'flutterkeep-f9b1a',
    authDomain: 'flutterkeep-f9b1a.firebaseapp.com',
    storageBucket: 'flutterkeep-f9b1a.firebasestorage.app',
    measurementId: 'G-YZMBYY7PXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8qjjrNy51RUdYrcSUMKbYzCxPqAKkCPU',
    appId: '1:509492408638:android:0adc31e0c9dedbb11efc6f',
    messagingSenderId: '509492408638',
    projectId: 'flutterkeep-f9b1a',
    storageBucket: 'flutterkeep-f9b1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2joRnSMr2_ghADXEH4mxoHcxZ8ch_zf4',
    appId: '1:509492408638:ios:b67015b870a6589d1efc6f',
    messagingSenderId: '509492408638',
    projectId: 'flutterkeep-f9b1a',
    storageBucket: 'flutterkeep-f9b1a.firebasestorage.app',
    iosBundleId: 'com.example.keepNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2joRnSMr2_ghADXEH4mxoHcxZ8ch_zf4',
    appId: '1:509492408638:ios:b67015b870a6589d1efc6f',
    messagingSenderId: '509492408638',
    projectId: 'flutterkeep-f9b1a',
    storageBucket: 'flutterkeep-f9b1a.firebasestorage.app',
    iosBundleId: 'com.example.keepNotes',
  );
}
